import { useCallback, useEffect, useRef, useState } from 'react';
import { Download, Film, Layers, Pencil, Plus, Server, Trash2, Tv } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import DataTable from '../components/DataTable';
import Modal from '../components/Modal';
import api, { apiError } from '../services/api';
import { deleteChannelSelection } from '../services/catalogDeletion';
const kinds={live_channels:'TV en vivo',movies:'Películas',categories:'Categorías'};
const blank={nombre:'',titulo:'',category_id:'',manifest_url:'',license_url:'',drm_type:'none',logo_url:'',poster_url:'',slug:'',tipo:'general',activo:true};
const blankXtream=providers=>({mode:'connect',providers,name:'Mi proveedor Xtream',baseUrl:'',username:'',password:'',userAgent:'',referer:'',preferredOutput:'auto'});
export default function ContentPage(){
 const [kind,setKind]=useState('live_channels'),[rows,setRows]=useState([]),[categories,setCategories]=useState([]),[form,setForm]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 const [deleteTarget,setDeleteTarget]=useState(null),[deleting,setDeleting]=useState(false);
 const [catalogSelected,setCatalogSelected]=useState(new Set()),[bulkDeleteOpen,setBulkDeleteOpen]=useState(false),[bulkDeleting,setBulkDeleting]=useState(false);
 const [importer,setImporter]=useState(null),[selected,setSelected]=useState(new Set()),[importing,setImporting]=useState(false),[importError,setImportError]=useState('');
 const [xtream,setXtream]=useState(null),[xtreamSelected,setXtreamSelected]=useState(new Set()),[xtreamBusy,setXtreamBusy]=useState(false),[xtreamError,setXtreamError]=useState('');
 const xtreamGeneration=useRef(0);
 const load=useCallback(async()=>{try{const [r,c]=await Promise.all([api.get(`/admin/v2/content/${kind}`),api.get('/admin/v2/content/categories')]);const nextRows=r.data.data;setRows(nextRows);setCategories(c.data.data);setCatalogSelected(current=>new Set([...current].filter(id=>nextRows.some(row=>Number(row.id)===Number(id)))));}catch(e){setError(apiError(e));}},[kind]);
 useEffect(()=>{setRows([]);setCatalogSelected(new Set());setBulkDeleteOpen(false);setError('');void load();},[load]);
 const change=(key,value)=>setForm({...form,[key]:value});
 const save=async e=>{e.preventDefault();setSaving(true);setError('');try{
  const data=kind==='categories'?{nombre:form.nombre,slug:form.slug,tipo:'general',activo:form.activo}:{category_id:form.category_id?Number(form.category_id):null,manifest_url:form.manifest_url||null,license_url:form.drm_type==='widevine'?form.license_url:null,drm_type:form.drm_type,activo:form.activo,...(kind==='movies'?{titulo:form.titulo,poster_url:form.poster_url||null}:{nombre:form.nombre,logo_url:form.logo_url||null})};
  if(form.id)await api.put(`/admin/v2/content/${kind}/${form.id}`,data);else await api.post(`/admin/v2/content/${kind}`,data);
  setForm(null);setNotice('Catálogo actualizado. Los cambios ya están disponibles para la app.');await load();
 }catch(err){setError(apiError(err));}finally{setSaving(false);}};
 const remove=async()=>{if(!deleteTarget)return;setDeleting(true);setError('');try{
  await api.delete(`/admin/v2/content/${kind}/${deleteTarget.id}`);const name=deleteTarget.nombre||deleteTarget.titulo;
  setDeleteTarget(null);setNotice(`${kind==='categories'?'Categoría':'Contenido'} “${name}” eliminado${kind==='categories'?'a':''}. ${kind==='categories'?'Los canales y películas relacionados permanecen sin categoría.':'Ya no aparecerá en la app.'}`);await load();
 }catch(err){setError(apiError(err));}finally{setDeleting(false);}};
 const toggleCatalogRow=id=>{if(bulkDeleting)return;setCatalogSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});};
 const toggleAllCatalogRows=checked=>{if(!bulkDeleting)setCatalogSelected(new Set(checked?rows.map(row=>row.id):[]));};
 const removeSelectedChannels=async()=>{if(!catalogSelected.size||bulkDeleting)return;setBulkDeleting(true);setError('');setNotice('');let deletedCount=0;try{
  const result=await deleteChannelSelection([...catalogSelected],ids=>api.delete('/admin/v2/content/live_channels',{data:{ids}}),progress=>{deletedCount=progress.deleted;setNotice(`Eliminando canales: ${progress.processed} de ${progress.total} procesados…`);});
  const count=result.deleted;setBulkDeleteOpen(false);setCatalogSelected(new Set());setNotice(`${count} canal${count===1?'':'es'} eliminado${count===1?'':'s'}.${result.missing?` ${result.missing} ya no existían; la lista se actualizó.`:' Ya no aparecerán en la aplicación.'}`);await load();
 }catch(err){setBulkDeleteOpen(false);setNotice(deletedCount?`${deletedCount} canales eliminados antes de la interrupción. Revisa la selección restante antes de reintentar.`:'');setError(apiError(err,'No se pudieron eliminar los canales seleccionados'));await load();}finally{setBulkDeleting(false);}};
 const loadCountryPreview=async(countryCode,countries)=>{setImporter(current=>({...current,countries,countryCode,loading:true,items:[],summary:null,source:null}));setSelected(new Set());setImportError('');try{
  const response=await api.get(`/admin/v2/content/import/iptv-org/${countryCode}/preview`);const data=response.data.data;const limit=data.limits?.maxSelection||50;
  setImporter({...data,countries,countryCode,loading:false});setSelected(new Set(data.items.filter(item=>item.trialEligible&&!item.existing).slice(0,limit).map(item=>item.sourceId)));
 }catch(err){setImporter(current=>({...current,countries,countryCode,loading:false}));setImportError(apiError(err));}};
 const openImporter=async()=>{setImporter({loading:true,items:[],summary:null,source:null,countries:[],countryCode:'py'});setSelected(new Set());setImportError('');try{
  const response=await api.get('/admin/v2/content/import/iptv-org/countries');const countries=response.data.data;const initial=countries.some(country=>country.code==='py')?'py':countries[0]?.code;
  if(!initial)throw new Error('iptv-org no devolvió países disponibles');await loadCountryPreview(initial,countries);
 }catch(err){setImporter(current=>({...current,loading:false}));setImportError(apiError(err));}};
 const toggleChannel=sourceId=>setSelected(current=>{const next=new Set(current);if(next.has(sourceId))next.delete(sourceId);else if(next.size<(importer.limits?.maxSelection||50))next.add(sourceId);else setImportError(`Puedes importar hasta ${importer.limits?.maxSelection||50} canales por lote.`);return next;});
 const importChannels=async()=>{setImporting(true);setImportError('');try{
  const response=await api.post(`/admin/v2/content/import/iptv-org/${importer.countryCode}`,{sourceIds:[...selected]},{timeout:90000});
  const result=response.data.data;const unavailable=result.unavailable.length;const reasons=result.unavailable.slice(0,2).map(item=>`${item.name}: ${item.reason}`).join(' · ');const remaining=Math.max(0,unavailable-2);
  setNotice(`${result.imported.length} canal${result.imported.length===1?'':'es'} de ${result.country.name} importado${result.imported.length===1?'':'s'}${unavailable?`; ${unavailable} omitido${unavailable===1?'':'s'} (${reasons}${remaining?` · y ${remaining} más`:''})`:''}.`);
  setImporter(null);setSelected(new Set());await load();
 }catch(err){setImportError(apiError(err));}finally{setImporting(false);}};
 const configureNewXtream=(providers=xtream?.providers||[])=>{xtreamGeneration.current+=1;setXtreamBusy(false);setXtreamError('');setXtreamSelected(new Set());setXtream(blankXtream(providers));};
 const closeXtream=()=>{xtreamGeneration.current+=1;setXtreamBusy(false);setXtream(null);};
 const loadXtreamStreams=async(providerId,filters={},generation=xtreamGeneration.current)=>{setXtreamBusy(true);setXtreamError('');setXtreamSelected(new Set());try{
  const params={search:filters.search||'',categoryId:filters.categoryId||'',limit:100};
  const response=await api.get(`/admin/v2/content/import/xtream/providers/${providerId}/streams`,{params,timeout:60000});const data=response.data.data;
  if(generation!==xtreamGeneration.current)return;
  setXtream(current=>({...current,...data,mode:'streams',providerId:Number(providerId),search:params.search,categoryId:params.categoryId}));
  setXtreamSelected(new Set(data.items.filter(item=>!item.imported).slice(0,data.limits?.maxSelection||50).map(item=>item.streamId)));
 }catch(err){if(generation!==xtreamGeneration.current)return;setXtreamError(apiError(err));setXtream(current=>({...current,mode:'streams',providerId:Number(providerId),items:current?.items||[],categories:current?.categories||[]}));}finally{if(generation===xtreamGeneration.current)setXtreamBusy(false);}};
 const openXtreamImporter=async()=>{const generation=++xtreamGeneration.current;setXtream({mode:'loading',providers:[]});setXtreamSelected(new Set());setXtreamError('');try{
  const response=await api.get('/admin/v2/content/import/xtream/providers');if(generation!==xtreamGeneration.current)return;const providers=response.data.data;
  if(!providers.length){setXtream(blankXtream(providers));return;}
  setXtream({mode:'select',providers,providerId:providers[0].id});
 }catch(err){if(generation!==xtreamGeneration.current)return;setXtreamError(apiError(err));setXtream(blankXtream([]));}};
 const connectXtream=async e=>{e.preventDefault();setXtreamBusy(true);setXtreamError('');try{
  const response=await api.post('/admin/v2/content/import/xtream/providers',{name:xtream.name,baseUrl:xtream.baseUrl,username:xtream.username,password:xtream.password,userAgent:xtream.userAgent,referer:xtream.referer,preferredOutput:xtream.preferredOutput},{timeout:60000});
  const provider=response.data.data.provider;const providers=[...(xtream.providers||[]),provider];setXtream({mode:'loading',providers,providerId:provider.id,search:'',categoryId:''});await loadXtreamStreams(provider.id);
 }catch(err){setXtreamError(apiError(err));}finally{setXtreamBusy(false);}};
 const toggleXtream=streamId=>setXtreamSelected(current=>{const next=new Set(current);if(next.has(streamId))next.delete(streamId);else if(next.size<(xtream.limits?.maxSelection||50))next.add(streamId);else setXtreamError(`Puedes importar hasta ${xtream.limits?.maxSelection||50} canales por lote.`);return next;});
 const importXtream=async()=>{setXtreamBusy(true);setXtreamError('');try{
  const response=await api.post(`/admin/v2/content/import/xtream/providers/${xtream.providerId}/import`,{streamIds:[...xtreamSelected]},{timeout:90000});const count=response.data.data.imported.length;
  setNotice(`${count} canal${count===1?'':'es'} Xtream importado${count===1?'':'s'}. Las credenciales quedan cifradas y no se envían al catálogo.`);setXtream(null);setXtreamSelected(new Set());await load();
 }catch(err){setXtreamError(apiError(err));}finally{setXtreamBusy(false);}};
 return <><PageHeader eyebrow="App Android" title="Tu catálogo" description="Administra las categorías, canales y películas que verán tus clientes." action={<button className="primary-button" onClick={()=>{setError('');setForm({...blank});}}><Plus size={18}/>Agregar</button>}/>
 {notice&&<div className="alert alert--success">{notice}</div>}{error&&!form&&!deleteTarget&&!bulkDeleteOpen&&<div className="alert alert--error">{error}</div>}
 <div className="toolbar">{Object.entries(kinds).map(([key,title])=><button key={key} className={kind===key?'primary-button':'secondary-button'} onClick={()=>{setKind(key);setForm(null);setDeleteTarget(null);setCatalogSelected(new Set());setNotice('');}}>{key==='live_channels'?<Tv size={18}/>:key==='movies'?<Film size={18}/>:<Layers size={18}/>} {title}</button>)}{kind==='live_channels'&&<><button className="secondary-button toolbar__import" onClick={openXtreamImporter}><Server size={18}/>Importar Xtream</button><button className="secondary-button" onClick={openImporter}><Download size={18}/>FAST público (prueba)</button></>}</div>
 {kind==='live_channels'&&rows.length>0&&<div className={`bulk-selection-bar ${catalogSelected.size?'bulk-selection-bar--active':''}`}><div><strong>{catalogSelected.size?`${catalogSelected.size} canal${catalogSelected.size===1?'':'es'} seleccionado${catalogSelected.size===1?'':'s'}`:'Selecciona canales para administrarlos'}</strong><span>{catalogSelected.size===rows.length&&rows.length>0?'Todos los canales están seleccionados':'Puedes elegirlos de a uno o seleccionar todos. Los catálogos grandes se eliminan por lotes.'}</span></div><div className="button-row"><button type="button" className="secondary-button" disabled={bulkDeleting} onClick={()=>toggleAllCatalogRows(catalogSelected.size!==rows.length)}>{catalogSelected.size===rows.length?'Deseleccionar todos':'Seleccionar todos'}</button>{catalogSelected.size>0&&<button type="button" className="secondary-button" disabled={bulkDeleting} onClick={()=>setCatalogSelected(new Set())}>Quitar selección</button>}<button type="button" className="danger-button" disabled={bulkDeleting||!catalogSelected.size} onClick={()=>{setError('');setBulkDeleteOpen(true);}}><Trash2 size={16}/>Eliminar seleccionados{catalogSelected.size?` (${catalogSelected.size})`:''}</button></div></div>}
 <section className="panel-card panel-card--table"><DataTable rows={rows} columns={[{key:'nombre',label:'Nombre',render:r=><strong>{r.nombre||r.titulo}</strong>},{key:'activo',label:'Estado',render:r=><span className={`status-pill ${r.activo?'status-pill--ok':'status-pill--muted'}`}>{r.activo?'Visible':'Oculto'}</span>},...(kind!=='categories'?[{key:'category_id',label:'Categoría',render:r=>categories.find(category=>Number(category.id)===Number(r.category_id))?.nombre||'Sin categoría'},{key:'manifest_url',label:'Reproducción',render:r=>r.xtream_provider_id?'Xtream configurado':r.manifest_url?'Fuente configurada':'Pendiente de fuente'}]:[{key:'slug',label:'Identificador'}])]} selection={kind==='live_channels'?{selectedIds:catalogSelected,someSelected:catalogSelected.size>0,allSelected:rows.length>0&&catalogSelected.size===rows.length,onToggle:toggleCatalogRow,onToggleAll:toggleAllCatalogRows,selectAllLabel:'Seleccionar todos los canales',rowLabel:'Seleccionar canal'}:undefined} actions={r=><><button className="mini-button" aria-label={`Modificar ${r.nombre||r.titulo}`} onClick={()=>{setError('');setNotice('');setForm({...blank,...r});}}><Pencil size={15}/>Modificar</button><button className="mini-button mini-button--danger" aria-label={`Eliminar ${r.nombre||r.titulo}`} onClick={()=>{setError('');setNotice('');setDeleteTarget(r);}}><Trash2 size={15}/>Eliminar</button></>}/></section>
 {kind!=='categories'&&<p className="catalog-note">Agrega fuentes HTTP o HTTPS de tu servicio autorizado. HTTP se admite para proveedores heredados, pero no cifra la señal ni las credenciales.</p>}
 {form&&<Modal title={`${form.id?'Editar':'Agregar'} · ${kinds[kind]}`} onClose={()=>!saving&&setForm(null)}><form className="form-grid" onSubmit={save}>
 {error&&<div className="alert alert--error form-grid__full">{error}</div>}
 <label className="form-grid__full">Nombre<input required maxLength={120} value={kind==='movies'?form.titulo:form.nombre} onChange={e=>change(kind==='movies'?'titulo':'nombre',e.target.value)}/></label>
 {kind==='categories'?<label className="form-grid__full">Identificador<input required pattern="[a-z0-9-]+" placeholder="deportes" value={form.slug} onChange={e=>change('slug',e.target.value)}/></label>:<>
 <label>Categoría<select value={form.category_id||''} onChange={e=>change('category_id',e.target.value)}><option value="">Sin categoría</option>{categories.map(c=><option value={c.id} key={c.id}>{c.nombre}{c.activo?'':' (oculta)'}</option>)}</select></label>
 <label>Protección<select value={form.drm_type||'none'} onChange={e=>change('drm_type',e.target.value)}><option value="none">Sin DRM</option><option value="widevine">Widevine</option></select></label>
 <label className="form-grid__full">URL del video o canal<input type="url" placeholder="http://… o https://…" value={form.manifest_url||''} onChange={e=>change('manifest_url',e.target.value)}/></label>
 {form.drm_type==='widevine'&&<><label className="form-grid__full">URL de licencia para clientes<input required type="url" value={form.license_url||''} onChange={e=>change('license_url',e.target.value)}/></label><small className="form-grid__full">Usa una URL apta para el reproductor. Los secretos maestros deben gestionarse en el servidor del proveedor.</small></>}
 <label className="form-grid__full">Logo o portada (HTTPS)<input type="url" value={(kind==='movies'?form.poster_url:form.logo_url)||''} onChange={e=>change(kind==='movies'?'poster_url':'logo_url',e.target.value)}/></label></>}
 <label className="checkbox-field form-grid__full"><input type="checkbox" checked={form.activo} onChange={e=>change('activo',e.target.checked)}/>Visible en la app</label>
 <div className="form-actions form-grid__full"><button type="button" className="secondary-button" disabled={saving} onClick={()=>setForm(null)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?'Guardando…':'Guardar'}</button></div>
 </form></Modal>}
 {deleteTarget&&<Modal title={`Eliminar · ${kinds[kind]}`} onClose={()=>!deleting&&setDeleteTarget(null)}><div className="delete-confirmation">
  <div className="delete-confirmation__icon"><Trash2 size={24}/></div>
  <div><h3>¿Eliminar “{deleteTarget.nombre||deleteTarget.titulo}”?</h3><p>{kind==='categories'?'La categoría desaparecerá, pero sus canales y películas se conservarán como “Sin categoría”.':'El contenido desaparecerá del panel y de la aplicación. Esta acción no se puede deshacer.'}</p></div>
 </div>{error&&<div className="alert alert--error">{error}</div>}<div className="form-actions"><button type="button" className="secondary-button" disabled={deleting} onClick={()=>setDeleteTarget(null)}>Conservar</button><button type="button" className="danger-button" disabled={deleting} onClick={()=>void remove()}><Trash2 size={16}/>{deleting?'Eliminando…':'Eliminar definitivamente'}</button></div></Modal>}
 {bulkDeleteOpen&&<Modal title="Eliminar canales seleccionados" onClose={()=>{if(!bulkDeleting){setError('');setBulkDeleteOpen(false);}}}><div className="delete-confirmation">
  <div className="delete-confirmation__icon"><Trash2 size={24}/></div>
  <div><h3>¿Eliminar {catalogSelected.size} canal{catalogSelected.size===1?'':'es'}?</h3><p>Los canales seleccionados desaparecerán inmediatamente del panel y de la aplicación. Esta acción no se puede deshacer.</p></div>
 </div>{error&&<div className="alert alert--error">{error}</div>}<div className="form-actions"><button type="button" className="secondary-button" disabled={bulkDeleting} onClick={()=>{setError('');setBulkDeleteOpen(false);}}>Conservar canales</button><button type="button" className="danger-button" disabled={bulkDeleting} onClick={()=>void removeSelectedChannels()}><Trash2 size={16}/>{bulkDeleting?'Eliminando…':`Eliminar ${catalogSelected.size}`}</button></div></Modal>}
 {importer&&<Modal wide title="Catálogo FAST público · prueba" onClose={()=>!importing&&setImporter(null)}>
  <label className="import-country">País<select value={importer.countryCode} disabled={importing||!importer.countries.length} onChange={e=>void loadCountryPreview(e.target.value,importer.countries)}>{importer.countries.map(country=><option key={country.code} value={country.code}>{country.flag} {country.name}</option>)}</select></label>
  {importer.loading?<div className="loading-panel">Descargando la lista del país seleccionado…</div>:<>
   {importError&&<div className="alert alert--error">{importError}</div>}
   {importer.summary&&<div className="import-summary"><span><strong>{importer.summary.total}</strong>Total</span><span><strong>{importer.summary.importable}</strong>Disponibles</span><span><strong>{importer.summary.existing}</strong>Ya agregados</span><span><strong>{importer.summary.excluded}</strong>Excluidos</span></div>}
   {importer.source&&<p className="import-note">Selecciona las señales disponibles del país elegido. HTTPS está admitido y HTTP se admite cuando está habilitado en el servidor. Cada canal se comprueba antes de guardarse. Fuente: <a href={importer.source.url} target="_blank" rel="noreferrer">{importer.source.name}</a>.</p>}
   {importer.items?.length?<div className="import-table table-wrap"><table><thead><tr><th><input aria-label="Seleccionar los primeros canales de prueba disponibles" type="checkbox" checked={selected.size>0&&selected.size===Math.min(importer.items.filter(item=>item.trialEligible&&!item.existing).length,importer.limits?.maxSelection||50)} onChange={e=>setSelected(new Set(e.target.checked?importer.items.filter(item=>item.trialEligible&&!item.existing).slice(0,importer.limits?.maxSelection||50).map(item=>item.sourceId):[]))}/></th><th>Canal</th><th>Servidor</th><th>Estado</th></tr></thead><tbody>{importer.items.map(item=>{
    const disabled=!item.trialEligible||item.existing;const limitReached=!selected.has(item.sourceId)&&selected.size>=(importer.limits?.maxSelection||50);return <tr key={item.sourceId}><td data-label="Elegir"><input aria-label={`Seleccionar ${item.name}`} type="checkbox" disabled={disabled||limitReached} checked={selected.has(item.sourceId)} onChange={()=>toggleChannel(item.sourceId)}/></td><td data-label="Canal"><strong>{item.name}</strong>{item.hasCustomHeaders&&<small className="import-detail">Incluye cabeceras de reproducción</small>}</td><td data-label="Servidor">{item.manifestHost||'—'}</td><td data-label="Estado"><span className={`status-pill ${item.existing?'status-pill--muted':item.trialEligible?'status-pill--ok':'status-pill--fallido'}`}>{item.existing?'Ya agregado':item.trialEligible?'Listo para comprobar':item.trialReason||'Excluido de la prueba'}</span></td></tr>;
   })}</tbody></table></div>:!importError&&<div className="empty-inline">No se encontraron canales en la lista.</div>}
   <div className="form-actions import-actions"><button type="button" className="secondary-button" disabled={importing} onClick={()=>setImporter(null)}>Cancelar</button><button type="button" className="primary-button" disabled={importing||selected.size===0} onClick={importChannels}>{importing?'Comprobando e importando…':`Comprobar e importar (${selected.size})`}</button></div>
  </>}
 </Modal>}
 {xtream&&<Modal wide title="Importar canales de Xtream Codes" onClose={()=>!xtreamBusy&&closeXtream()}>
  {xtream.mode==='loading'?<><div className="loading-panel">Cargando las cuentas Xtream guardadas…</div><div className="form-actions import-actions"><button type="button" className="secondary-button" onClick={closeXtream}>Cancelar</button><button type="button" className="primary-button" onClick={()=>configureNewXtream([])}><Plus size={16}/>Configurar cuenta nueva</button></div></>:xtream.mode==='connect'?<form className="form-grid" onSubmit={connectXtream}>
   {xtreamError&&<div className="alert alert--error form-grid__full">{xtreamError}</div>}
   <p className="import-note form-grid__full">Conecta una cuenta autorizada. El usuario y la contraseña se cifran en el servidor y nunca se muestran en el catálogo ni se guardan en la app.</p>
   <label className="form-grid__full">Nombre del proveedor<input required maxLength={120} placeholder="Mi proveedor Xtream" value={xtream.name||''} onChange={e=>setXtream({...xtream,name:e.target.value})}/></label>
   <label className="form-grid__full">Servidor Xtream<input required type="url" placeholder="http://servidor:puerto" value={xtream.baseUrl||''} onChange={e=>setXtream({...xtream,baseUrl:e.target.value})}/></label>
   <label>Usuario<input required autoComplete="username" value={xtream.username||''} onChange={e=>setXtream({...xtream,username:e.target.value})}/></label>
   <label>Contraseña<input required type="password" autoComplete="new-password" value={xtream.password||''} onChange={e=>setXtream({...xtream,password:e.target.value})}/></label>
   <label>Formato preferido<select value={xtream.preferredOutput||'auto'} onChange={e=>setXtream({...xtream,preferredOutput:e.target.value})}><option value="auto">Automático</option><option value="m3u8">HLS (.m3u8)</option><option value="ts">Transport Stream (.ts)</option></select></label>
   <label>User-Agent autorizado<input maxLength={300} placeholder="Opcional" value={xtream.userAgent||''} onChange={e=>setXtream({...xtream,userAgent:e.target.value})}/></label>
   <label className="form-grid__full">Referer autorizado<input type="url" placeholder="https://portal-del-proveedor.example/" value={xtream.referer||''} onChange={e=>setXtream({...xtream,referer:e.target.value})}/></label>
   <div className="form-actions form-grid__full"><button type="button" className="secondary-button" disabled={xtreamBusy} onClick={closeXtream}>Cancelar</button><button className="primary-button" disabled={xtreamBusy}>{xtreamBusy?'Validando cuenta…':'Conectar y cargar canales'}</button></div>
  </form>:xtream.mode==='select'?<>
   <p className="import-note">Elige una cuenta guardada para consultar sus canales o configura otra cuenta Xtream.</p>
   <div className="form-grid"><label className="form-grid__full">Cuenta guardada<select value={xtream.providerId||''} onChange={e=>setXtream({...xtream,providerId:Number(e.target.value)})}>{(xtream.providers||[]).map(provider=><option key={provider.id} value={provider.id}>{provider.name}{provider.status?` · ${provider.status}`:''}</option>)}</select></label></div>
   <div className="form-actions import-actions"><button type="button" className="secondary-button" onClick={()=>configureNewXtream(xtream.providers)}><Plus size={16}/>Configurar cuenta nueva</button><button type="button" className="primary-button" disabled={!xtream.providerId} onClick={()=>void loadXtreamStreams(xtream.providerId)}>Cargar canales</button></div>
  </>:<>
   {xtreamError&&<div className="alert alert--error">{xtreamError}</div>}
   <div className="form-grid">
    <label>Proveedor<select value={xtream.providerId||''} disabled={xtreamBusy} onChange={e=>void loadXtreamStreams(e.target.value)}>{(xtream.providers||[]).map(provider=><option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></label>
    <label>Categoría<select value={xtream.categoryId||''} disabled={xtreamBusy} onChange={e=>void loadXtreamStreams(xtream.providerId,{search:xtream.search,categoryId:e.target.value})}><option value="">Todas las categorías</option>{(xtream.categories||[]).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label>
    <label className="form-grid__full">Buscar canal<input placeholder="Nombre del canal" value={xtream.search||''} onChange={e=>setXtream({...xtream,search:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void loadXtreamStreams(xtream.providerId,{search:xtream.search,categoryId:xtream.categoryId});}}}/></label>
   </div>
   <div className="form-actions"><button type="button" className="secondary-button" disabled={xtreamBusy} onClick={()=>configureNewXtream(xtream.providers)}><Plus size={16}/>Configurar cuenta nueva</button><button type="button" className="secondary-button" disabled={xtreamBusy} onClick={()=>void loadXtreamStreams(xtream.providerId,{search:xtream.search,categoryId:xtream.categoryId})}>{xtreamBusy?'Consultando…':'Buscar'}</button></div>
   {xtream.account&&<div className="import-summary"><span><strong>{xtream.pagination?.total||0}</strong>Resultados</span><span><strong>{xtream.account.status}</strong>Cuenta</span><span><strong>{xtream.account.activeConnections}/{xtream.account.maxConnections||'—'}</strong>Conexiones</span><span><strong>{xtream.account.expiresAt?new Date(xtream.account.expiresAt).toLocaleDateString('es-PY'):'—'}</strong>Vencimiento</span></div>}
   <p className="import-note">Se importan el nombre, logo, categoría y <code>stream_id</code>. La app recibe un enlace temporal de TV Digital al iniciar la reproducción.</p>
   {xtream.items?.length?<div className="import-table table-wrap"><table><thead><tr><th><input aria-label="Seleccionar canales Xtream disponibles" type="checkbox" checked={xtreamSelected.size>0&&xtreamSelected.size===Math.min(xtream.items.filter(item=>!item.imported).length,xtream.limits?.maxSelection||50)} onChange={e=>setXtreamSelected(new Set(e.target.checked?xtream.items.filter(item=>!item.imported).slice(0,xtream.limits?.maxSelection||50).map(item=>item.streamId):[]))}/></th><th>Canal</th><th>Categoría</th><th>Formato</th><th>Estado</th></tr></thead><tbody>{xtream.items.map(item=>{
    const category=xtream.categories?.find(entry=>entry.id===item.categoryId)?.name||'Sin categoría';const limitReached=!xtreamSelected.has(item.streamId)&&xtreamSelected.size>=(xtream.limits?.maxSelection||50);return <tr key={item.streamId}><td data-label="Elegir"><input aria-label={`Seleccionar ${item.name}`} type="checkbox" disabled={item.imported||limitReached} checked={xtreamSelected.has(item.streamId)} onChange={()=>toggleXtream(item.streamId)}/></td><td data-label="Canal"><strong>{item.name}</strong><small className="import-detail">ID {item.streamId}</small></td><td data-label="Categoría">{category}</td><td data-label="Formato">{item.container.toUpperCase()}</td><td data-label="Estado"><span className={`status-pill ${item.imported?'status-pill--muted':'status-pill--ok'}`}>{item.imported?'Ya importado':'Disponible'}</span></td></tr>;
   })}</tbody></table></div>:!xtreamBusy&&!xtreamError&&<div className="empty-inline">No se encontraron canales con esos filtros.</div>}
   <div className="form-actions import-actions"><button type="button" className="secondary-button" disabled={xtreamBusy} onClick={closeXtream}>Cancelar</button><button type="button" className="primary-button" disabled={xtreamBusy||xtreamSelected.size===0} onClick={importXtream}>{xtreamBusy?'Importando…':`Importar (${xtreamSelected.size})`}</button></div>
  </>}
 </Modal>}</>;
}
